[news]
title = "로아리포트 ─ 분아별 동향 ─ 전체"
url = "https://report.roa.ai/news"
entrySelector = "div.articleItems article.articleItem__card"
titleSelector = "a.title"
linkSelector = "a.title"
contentSelector = "div.articleItem__Col--right p"
imageSelector = "figure.articleItem__Col--left"
waitForSelector = "div.articleItems article.articleItem__card"

[news_it]
title = "로아리포트 ─ 분아별 동향 ─ IT"
url = "https://report.roa.ai/news/it"
entrySelector = "div.articleItems article.articleItem__card"
titleSelector = "a.title"
linkSelector = "a.title"
contentSelector = "div.articleItem__Col--right p"
imageSelector = "figure.articleItem__Col--left"
waitForSelector = "div.articleItems article.articleItem__card"

[news_media]
title = "로아리포트 ─ 분아별 동향 ─ 미디어"
url = "https://report.roa.ai/news/media"
entrySelector = "div.articleItems article.articleItem__card"
titleSelector = "a.title"
linkSelector = "a.title"
contentSelector = "div.articleItem__Col--right p"
waitForSelector = "div.articleItems article.articleItem__card"