[news]
title = "로아리포트 ─ 분아별 동향 ─ 전체"
url = "https://report.roa.ai/news"
entrySelector = "section.mg.mb-92.position-relative.card div.articleItems article.articleItem__card"
titleSelector = "a.title"
linkSelector = "a.articleItem__link"
contentSelector = "div.articleItem__Col--right p"
waitUntil = "networkidle"

[insight]
title = "로아리포트 ─ 심층분석 ─ 전체"
url = "https://report.roa.ai/insight"
entrySelector = "div.articleItems article.articleItem__card"
titleSelector = "a.title"
linkSelector = "a.articleItem__link"
contentSelector = "div.articleItem__Col--right p"
dateSelector = "span.articleItem__published"
dateFormat = "yy. MM. dd"
waitUntil = "networkidle"
